#!/bin/bash

echo "Build hook running"
docker build \
  --build-arg VCS_REF=`git rev-parse — short HEAD` \
  --build-arg CACHE_TAG=1.0.1 \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  -t $IMAGE_NAME .